'use client';
import{useEffect,useState}from'react';
const wa='https://wa.me/5594991372010?text='+encodeURIComponent('Olá, Wana! Gostaria de agendar uma consulta de avaliação.');
const services=[
 {n:'01',title:'Harmonização íntima',text:'Protocolos personalizados para proporção, hidratação, sustentação e bem-estar da região íntima.',img:'/intima.jpg'},
 {n:'02',title:'Ninfo sem cortes',text:'Técnica não cirúrgica para redução e melhora estética dos pequenos lábios, conforme avaliação individual.',img:'/care.jpg'},
 {n:'03',title:'Clareamento íntimo',text:'Cuidado progressivo para uniformizar o tom da pele com segurança, conforto e acompanhamento.',img:'/skin.jpg'},
 {n:'04',title:'Harmonização glútea',text:'Planejamento de contorno, firmeza e proporção com técnica, anatomia e resultados elegantes.',img:'/body.jpg'},
 {n:'05',title:'Bioestimulação',text:'Estímulo de colágeno para qualidade de pele, sustentação e melhora gradual da região tratada.',img:'/detail.jpg'}];
function Flower(){return <svg className="flower" viewBox="0 0 120 120" aria-hidden="true"><g fill="none" stroke="currentColor"><ellipse cx="60" cy="31" rx="13" ry="28"/><ellipse cx="60" cy="31" rx="13" ry="28" transform="rotate(72 60 60)"/><ellipse cx="60" cy="31" rx="13" ry="28" transform="rotate(144 60 60)"/><ellipse cx="60" cy="31" rx="13" ry="28" transform="rotate(216 60 60)"/><ellipse cx="60" cy="31" rx="13" ry="28" transform="rotate(288 60 60)"/><circle cx="60" cy="60" r="6"/></g></svg>}
function Brand(){return <span className="brand"><b>Wana Lima</b><small>Estética íntima avançada</small></span>}
export default function Home(){const[menu,setMenu]=useState(false);const[open,setOpen]=useState(0);useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.14});document.querySelectorAll('.reveal,.mask').forEach(e=>o.observe(e));return()=>o.disconnect()},[]);return <main>
 <header><a href="#inicio"><Brand/></a><button className="menu" onClick={()=>setMenu(!menu)}>Menu</button><nav className={menu?'open':''}><a href="#sobre">Sobre</a><a href="#cuidados">Cuidados</a><a href="#wana">Wana</a><a className="round" href={wa}>Agendar consulta</a></nav></header>
 <section className="hero" id="inicio"><div className="heroGrid"/><Flower/><div className="heroTitle reveal"><p>SAÚDE FEMININA · PARAUAPEBAS</p><h1>Seu corpo.<br/>Sua história.<br/><i>Seu reencontro.</i></h1></div><div className="heroPhoto mask"><img src="/hero.jpg" alt="Mulher em momento de autocuidado e confiança"/><span>Estética que acolhe,<br/>não julga.</span></div><div className="heroNote reveal"><p>Harmonização íntima e glútea com conhecimento, respeito e propósito.</p><a href={wa}>CONVERSAR COM A WANA ↗</a></div><span className="scroll">DESCUBRA ↓</span></section>
 <section className="taboo" id="sobre"><div className="tabooLabel">01 / NOSSO PROPÓSITO</div><div className="tabooWords"><span className="reveal">Sem tabu.</span><span className="reveal">Sem julgamento.</span><span className="reveal"><i>Com escuta.</i></span></div><div className="tabooCopy reveal"><p>Existem desconfortos que muitas mulheres vivem em silêncio. Aqui, cada conversa começa com acolhimento e privacidade.</p><p>A estética íntima pode ser sobre beleza — mas também sobre conforto, segurança e a liberdade de se reconhecer no próprio corpo.</p></div></section>
 <section className="services" id="cuidados"><div className="servicesIntro"><p>02 / CUIDADOS</p><h2>Possibilidades<br/>para se sentir <i>bem.</i></h2><p>Cada procedimento depende de avaliação individual. Nenhuma história é igual à outra — e nenhum plano de cuidado também deve ser.</p></div><div className="serviceStack">{services.map((s,i)=><article key={s.title} className={open===i?'active':''} style={{top:`${85+i*18}px`,zIndex:i+1}}><button onClick={()=>setOpen(i)} aria-expanded={open===i}><span>{s.n}</span><h3>{s.title}</h3><i>{open===i?'—':'+'}</i></button><div className="serviceInside"><img src={s.img} alt={s.title}/><p>{s.text}</p><a href={wa}>Saber mais com privacidade ↗</a></div></article>)}</div></section>
 <section className="privacy"><div className="curtain left"/><div className="curtain right"/><div className="privacyContent reveal"><Flower/><p>Aqui, privacidade não é detalhe.</p><h2>É parte<br/>do cuidado.</h2><span>Atendimento individual · Ambiente reservado · Conversa sem julgamentos</span></div></section>
 <section className="interview" id="wana"><div className="portrait mask"><img src="/wana.jpg" alt="Enfermeira esteta Wana Lima"/><div>COREN 921.040<br/>CERTIFICAÇÃO INTERNACIONAL</div></div><div className="answers"><p>03 / WANA LIMA</p><h2>Ciência com<br/><i>sensibilidade.</i></h2><dl><div className="reveal"><dt>Quem cuida de você?</dt><dd>Wana Lima, enfermeira esteta, pós-graduada em Estética Avançada e Saúde da Mulher.</dd></div><div className="reveal"><dt>Qual é o seu olhar?</dt><dd>Resultados naturais construídos com planejamento, anatomia, precisão e respeito à individualidade.</dd></div><div className="reveal"><dt>O que move esse trabalho?</dt><dd>Ajudar mulheres a se reencontrarem com sua autoestima, seu conforto e sua própria história.</dd></div></dl><a href="https://www.instagram.com/wana_limaa/" target="_blank">ACOMPANHAR @WANA_LIMAA ↗</a></div></section>
 <section className="principles"><div><small>01</small><b>Escuta</b><p>Você fala no seu tempo. Toda dúvida merece atenção.</p></div><div><small>02</small><b>Segurança</b><p>Avaliação, indicação consciente e produtos biocompatíveis.</p></div><div><small>03</small><b>Naturalidade</b><p>Resultados elegantes, sem apagar a sua essência.</p></div><div><small>04</small><b>Privacidade</b><p>Respeito absoluto em todas as etapas do atendimento.</p></div></section>
 <section className="cta" id="contato"><div className="ctaFlower"><Flower/><Flower/></div><p>Talvez o primeiro passo seja só uma conversa.</p><h2>Vamos falar<br/><i>sobre você?</i></h2><a href={wa}>Agendar consulta pelo WhatsApp <b>↗</b></a><div className="info"><span><small>WHATSAPP</small>(94) 99137-2010</span><span><small>ENDEREÇO</small>Av. E, Quadra 55, Lote 14 · Beira Rio II<br/>Parauapebas, PA</span><span><small>INSTAGRAM</small>@wana_limaa</span></div></section>
 <footer><Brand/><p>© 2026 · Saúde feminina com respeito e propósito.</p><a href="#inicio">VOLTAR AO TOPO ↑</a></footer><a className="float" href={wa}>WhatsApp ↗</a>
 </main>}
